# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: basic
language: python
runtimeConfig:
  start:
    - "python3 ./agent_handoff.py"
database:
  hostname: localhost
  port: 5432
  username: postgres
  password: ${PGPASSWORD}
  app_db_name: basic
  migrate:
    - echo 'No migrations specified'
telemetry:
  logs:
    logLevel: INFO
